### ISSUE TITLE
Any way to output raw PPG signal to calculate HRV metrics?

### ISSUE THREAD

**Issue by Niteesh-Kalangi** [SamProell/yarppg#19]
I am trying to calculate HRV metrics from videos, and I think I need the raw PPG signal to do that. Is there any way I can get the code to output raw PPG signals? I need metrics of {'HR', 'SDRR', 'RMSSD', 'SDSD', 'pNN50'}.

**Comment by SamProell** [comment]
You can run the programm with `run-yarppg --savepath=./signals.csv` which will write a history of the recorded processor values after the window is closed.

Concerning HRV, you may need to consider that due to the low sampling rate (typically 30 frames per second on a webcam), some parameters may not be very accurate.

**Comment by Niteesh-Kalangi** [comment]
I was going to ask, what kind of data does that data outputted represent? Because its not a raw PPG signal right? So what do the columns represent, and how can they be used to get HRV metrics?

**Comment by SamProell** [comment]
It depends on the algorithm you processor you choose. By default, you get a bandpass-filtered version of the average green channel in the region of interest. 

For HRV, you would need to identify the heart beats in the output signal, then calculate the time differences between successive beats (in ECG this would be RR intervals - RRI). Then you could something like neurokit to calculate HRV https://neuropsychology.github.io/NeuroKit/examples/ecg_hrv/ecg_hrv.html

**Comment by soheilkooklan** [comment]
Hi There!

You're correct that accessing the raw PPG signal is essential for calculating video HRV metrics. As Sam mentioned, the output from the default algorithm is a bandpass-filtered version of the average green channel in the region of interest, which isn't precisely raw PPG but a processed version. This data can still be used to estimate heartbeats and calculate HRV metrics like SDRR, RMSSD, SDSD, pNN50, etc.

You can use a tool like NeuroKit to compute HRV from these signals (link: [NeuroKit HRV tutorial](https://neuropsychology.github.io/NeuroKit/examples/ecg_hrv/ecg_hrv.html)). However, the limitations of the low sampling rate (e.g., 30 fps for webcam data) may affect the accuracy of specific metrics, particularly those that rely on high temporal resolution.

If you're specifically after raw PPG, you might need to explore other hardware options, such as dedicated PPG sensors with higher sampling rates, to get more accurate HRV metrics.

I hope this helps! Let me know if you have any more questions.

**Comment by Niteesh-Kalangi** [comment]
Also, I see that in the code, you guys calculate heartbeats from peaks in hr.py with the from_peaks method. Could I just use that code and the pulse wave signal values to identify heartbeats and then use that for HRV? Or would you suggest using the outputted csv file for those calculations instead?

**Comment by SamProell** [comment]
I actually just this week updated the repo with a complete rework of the functionality. There is now also a documentation for most of the code.
You can go through the instructions here: https://samproell.github.io/yarppg/video_processing/ to get signal values directly for a video file. You can then detect heartbeats from there to do the HRV.

**Comment by Niteesh-Kalangi** [comment]
Whenever I try importing the yarppg package with this updated repo, I get this error:
Traceback (most recent call last):
  File "/Users/niteesh/repos/yarppg/tests/my_test.py", line 1, in <module>
    import yarppg
  File "/Users/niteesh/opt/anaconda3/envs/newrppg/lib/python3.9/site-packages/yarppg/__init__.py", line 28, in <module>
    from .containers import Color, RegionOfInterest, RppgResult
  File "/Users/niteesh/opt/anaconda3/envs/newrppg/lib/python3.9/site-packages/yarppg/containers.py", line 10, in <module>
    class RegionOfInterest:
  File "/Users/niteesh/opt/anaconda3/envs/newrppg/lib/python3.9/site-packages/yarppg/containers.py", line 15, in RegionOfInterest
    bg_mask: np.ndarray | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
